# -*- coding: utf-8 -*-
"""stock_market_UBER_live_share_price.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w0mCjoQLQGFbqWCP4uxLN8uti-LYYj-3

# **Stock market data using Yahoo Finance API**
"""

#pip install yfinance

# Import Libraries
import numpy as np
import pandas as pd
#import yahoo_finance as yf
import yfinance as yf
import plotly.graph_objs as go

"""How to get live market data per minutes"""

# Interval requered 1 minute
data = yf.download(tickers='UBER', period='5d', interval='1m') 
data

data = yf.download(tickers='UBER', period='5d', interval='1m') 

# declare figure
fig = go.Figure()

# Candlestick
fig.add_trace(go.Candlestick(x=data.index,
                             open=data['Open'],
                             high=data['High'],
                             low=data['Low'],
                             close=data['Close'], name = 'market data'))

# Add titles
fig.update_layout(
    title='UBER live share price evolution',
    yaxis_title='Stock Price (USD per Shares)'
)

# X_Axes
fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
                      dict(count=15, label='15m', step='minute', stepmode='backward'),
                      dict(count=45, label='45m', step='minute', stepmode='backward'),
                      dict(count=1, label='HTD', step='hour', stepmode='todate'),
                      dict(count=3, label='3h', step='hour', stepmode='backward'),
                      dict(step='all')
        ])
    )

)

#show
fig.show()