# -*- coding: utf-8 -*-
"""Live market Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r186vhzCOnV26kWeJH-RokAH1dUrZNPe
"""



#libraries
import numpy as np
import pandas as pd

#pip install yfinance

#Data Finance
import yfinance as yf

# Data vip
import plotly.graph_objs as go

"""# How to get live market data per minutes"""

data = yf.download(tickers='UBER', period='5d', interval='1m')
#Interval required 1 minute

data

data = yf.download(tickers='UBER', period='1d', interval='1m')
# Interval required, 1 minute

# Declare figure
fig = go.Figure()

# CandleStick
fig.add_trace(go.Candlestick(x=data.index,
                             open=data['Open'],
                             high=data['High'],
                             low=data['Low'],
                             close=data['Close'], name = 'market data'))

# Add titles
fig.update_layout(
    title = 'Uber live share price evolution',
    yaxis_title = 'Stock Price (USD per minutes)')

# X-Axis
fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=15, label='15m', step='minute', stepmode='backward'),
            dict(count=45, label='45m', step='minute', stepmode='backward'),
            dict(count=1, label='HTD', step='hour', stepmode='todate'),
            dict(count=2, label='1h', step='hour', stepmode='backward'),
            dict(step='all')
        ])
    )
)